name: Playwright Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
      run: chmod +x node_modules/.bin/playwright

        run: npx playwright install
      - name: Run Playwright tests
        run: npx playwright test 